---
# tasks file for eos tasks

- name: Arista EOS - Collect VRF data.
  eos_command:
    commands: show vrf
  register: raw_vrf_data
  when: vrfs_required

- name: Arista EOS - Determine VRFs from VRF data.
  set_fact:
    vrfs: "{{ raw_vrf_data | parse_eos_vrfs }}"
  when: vrfs_required

- name: Arista EOS - Build user VRF-aware commands.
  set_fact:
    vrf_command_list: "{{ vrf_command_list | update_with_vrfs(vrfs | default([])) }}"

- name: Arista EOS - Run user VRF-aware commands.
  ignore_errors: yes
  eos_command:
    commands: "{{ item }}"
  register: raw_command_data
  loop: "{{ vrf_command_list }}"