---
# tasks file for ios tasks

- name: Cisco IOS - Collect VRF data.
  block:
  - name: Cisco IOS - Run 'show vrf'.
    ios_command:
      commands: show vrf
    register: raw_vrf_data
  rescue:
  - name: Cisco IOS - Run 'show ip vrf'.
    ios_command:
      commands: show ip vrf
    register: raw_vrf_data
  when: vrfs_required

- name: Cisco IOS - Determine VRFs from VRF data.
  set_fact:
    vrfs: "{{ raw_vrf_data | parse_ios_vrfs }}"
  when: vrfs_required

- name: Cisco IOS - Build user VRF-aware commands.
  set_fact:
    vrf_commands: "{{ vrf_commands | update_with_vrfs(vrfs | default([])) }}"

- name: Cisco IOS - Run user VRF-aware commands.
  ignore_errors: yes
  ios_command:
    commands: "{{ item }}"
  register: raw_command_data
  loop: "{{ vrf_commands }}"