---
# tasks file for vrf_command

- name: Determine if user provided commands require VRF modifications.
  set_fact:
    vrfs_required: "{{ vrf_commands | check_for_vrfs }}"

- name: Run the Cisco NXOS VRF logic.
  include_tasks: nxos_tasks.yml
  when: ansible_network_os == 'nxos'

- name: Run the Cisco IOS VRF logic.
  include_tasks: ios_tasks.yml
  when: ansible_network_os == 'ios'

- name: Run the Arista EOS VRF logic.
  include_tasks: eos_tasks.yml
  when: ansible_network_os == 'eos'

- name: Clean up command output.
  set_fact:
    vrf_command_output: "{{ raw_command_data | clean_up_command_output }}"

- name: Show the show command output.
  debug:
    msg: "{{ vrf_command_output }}"