---
# tasks file for nxos tasks

- name: Cisco NXOS - Collect VRF data.
  nxos_command:
    commands: show vrf
  register: raw_vrf_data
  when: vrfs_required

- name: Cisco NXOS - Determine VRFs from VRF data.
  set_fact:
    vrfs: "{{ raw_vrf_data | parse_nxos_vrfs }}"
  when: vrfs_required

- name: Cisco NXOS - Build user VRF-aware commands.
  set_fact:
    vrf_commands: "{{ vrf_commands | update_with_vrfs(vrfs | default([])) }}"

- name: Cisco NXOS - Run user VRF-aware commands.
  ignore_errors: yes
  nxos_command:
    commands: "{{ item }}"
  register: raw_command_data
  loop: "{{ vrf_commands }}"